Repository MicroClub-USTHB/python-language, pull requests merged in 2020-10, with the labels that each got.

#2 Rpn
  Math_level3/factorial-recursive/README.md
  Math_level3/factorial-recursive/factorial-recursive.py
  Math_level3/reverse_polish_notation/README.md
  Math_level3/reverse_polish_notation/rpn.py
Labels: good first issue, hacktoberfest

#8 This fixes issue #4
  text-to-speech/text_to_speech.py
  text-to-speech/voices.py
Labels: Hacktoberfest

#9 Add files via upload
  DigitalClock/DigitalClock.py
Labels: hacktoberfest-accepted

#10 added a search program
  Recursif_Display_Of_Directory_Files/README.md
  Recursif_Display_Of_Directory_Files/recursif_display_directory_files.py
  TextSearch/README.md
  TextSearch/TextSearch.py
Labels: Hacktoberfest, hacktoberfest-accepted

#12 Create readme.md
  DigitalClock/readme.md
Labels: hacktoberfest-accepted

#11 Changed Recursif file
  Recursif_Display_Of_Directory_Files/README.md
  Recursif_Display_Of_Directory_Files/recursif_display_directory_files.py
  TextSearch/README.md
Labels: hacktoberfest-accepted

#13 added a classificaion algorithms folder containing one algorithm so far.
  Algorithms/classification/Fuzzy_C_Means.py
Labels: hacktoberfest-accepted

#14 Some ML predictions of US flights on-time arrivals
  Data_visualization_w_plt/Data_Representation_w_matplotlib.ipynb
  Data_visualization_w_plt/Data_vis_on_time_series.ipynb
  Data_visualization_w_plt/README.md
  flight_delay_prediction_w_Scikitlearn.ipynb
Labels: Hacktoberfest, hacktoberfest-accepted
